name: Build and Sign macOS Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to build (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: boqodo/cmdwise
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          ref: ${{ github.event.inputs.tag }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm install
      
      - name: Prepare certificates
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          # 创建临时目录
          mkdir -p ~/certs
          # 将证书写入文件
          echo "$APPLE_CERTIFICATE" | base64 --decode > ~/certs/dev-cert.p12
          # 创建 keychain
          security create-keychain -p "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" build.keychain
          # 导入证书
          security import ~/certs/dev-cert.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          # 设置权限
          security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" build.keychain
      
      - name: Build and Sign for macOS
        run: npm run dist:macos
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ~/certs/dev-cert.p12
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      
      - name: Cleanup
        if: always()
        run: |
          security delete-keychain build.keychain
          rm -rf ~/certs
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          artifacts: "release/*.dmg,release/*.zip"
          body: |
            ## 安装说明
            
            已经过 Apple 签名和公证，可以直接打开使用。
            
            ### macOS 安装方式
            1. 下载 DMG 文件
            2. 打开 DMG，将应用拖入应用程序文件夹
            3. 双击直接打开 CmdWise
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
